# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/polina/Documents/Programm-lab/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(726, 624)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 731, 601))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 701, 471))
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(10, 490, 701, 61))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 701, 471))
        self.label.setText("")
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 10, 701, 471))
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 490, 701, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 726, 24))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_Dataset = QtWidgets.QMenu(self.menuBar)
        self.menu_Dataset.setObjectName("menu_Dataset")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.actiondataset2 = QtWidgets.QAction(MainWindow)
        self.actiondataset2.setObjectName("actiondataset2")
        self.action_Dataset3 = QtWidgets.QAction(MainWindow)
        self.action_Dataset3.setObjectName("action_Dataset3")
        self.action_C_Dataset = QtWidgets.QAction(MainWindow)
        self.action_C_Dataset.setObjectName("action_C_Dataset")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu_Dataset.addAction(self.actiondataset2)
        self.menu_Dataset.addAction(self.action_Dataset3)
        self.menu_2.addAction(self.action_C_Dataset)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_Dataset.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Следующий котик"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Cats"))
        self.pushButton_2.setText(_translate("MainWindow", "Следующий песик"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Dogs"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_Dataset.setTitle(_translate("MainWindow", "Dataset"))
        self.menu_2.setTitle(_translate("MainWindow", "Аннотация"))
        self.actiondataset2.setText(_translate("MainWindow", "& Создать Dataset2"))
        self.action_Dataset3.setText(_translate("MainWindow", "Создать Dataset3"))
        self.action_C_Dataset.setText(_translate("MainWindow", "&Cоздать аннотацию исходного Dataset"))
        self.action_2.setText(_translate("MainWindow", "&Выбрать папку"))
        self.action_3.setText(_translate("MainWindow", "&Выход"))
